/*
 * ModusMate per-algo MLP model — generated by
 * modusmate_host.c_export.write_imai_model().
 *
 *   preprocessing algo : dog
 *   trained on dataset : rps
 *   input (host train) : 32x32x3 uint8
 *   input (firmware)   : 320x320x3 uint8 (downsampled inside IMAI_compute)
 *   hidden layer       : 32 units, ReLU
 *   output classes     : 3  (rock, paper, scissors)
 *
 * The firmware ABI expects float[8, 5] column-major output.  This
 * model writes its top-3 class probabilities into the
 * class-score lanes of slot 0 and sets the detection flag.  Class
 * indices beyond 3 are dropped because the firmware's
 * detection parser reads only those score lanes.
 */
#ifndef MODUSMATE_PERALGO_MODEL_H
#define MODUSMATE_PERALGO_MODEL_H

#include <stdbool.h>
#include <stdint.h>
#include "mtb_ml_model.h"

#define IMAI_API_FUNCTION

typedef int8_t  q7_t;
typedef int16_t q15_t;
typedef int32_t q31_t;
typedef int64_t q63_t;

#define IMAI_MODEL_ID {0xd6, 0xfb, 0xb1, 0x4f, 0x47, 0x05, 0xd3, 0xc4, 0x66, 0x89, 0xed, 0x8d, 0x0b, 0xe0, 0x8d, 0xe4}

#define IMAGINET_TYPES_NONE    (0x0)
#define IMAGINET_TYPES_FLOAT32 (0x14)
#define IMAGINET_TYPES_UINT8   (0x71)

/* datain [320,320,3] (307200 bytes) - matches the real RPS model. */
#define IMAI_DATAIN_RANK    (3)
#define IMAI_DATAIN_SHAPE   (((int[]){3, 320, 320})
#define IMAI_DATAIN_COUNT   (307200)
#define IMAI_DATAIN_TYPE    uint8_t
#define IMAI_DATAIN_TYPE_ID IMAGINET_TYPES_UINT8
#define IMAI_DATAIN_SHIFT   0
#define IMAI_DATAIN_OFFSET  0
#define IMAI_DATAIN_SCALE   1
#define IMAI_DATAIN_SYMBOLS { }

/* dataout [8,5] (160 bytes), column-major, matches the real RPS model. */
#define IMAI_DATAOUT_RANK    (2)
#define IMAI_DATAOUT_SHAPE   (((int[]){5, 8})
#define IMAI_DATAOUT_COUNT   (40)
#define IMAI_DATAOUT_TYPE    float
#define IMAI_DATAOUT_TYPE_ID IMAGINET_TYPES_FLOAT32
#define IMAI_DATAOUT_SHIFT   0
#define IMAI_DATAOUT_OFFSET  0
#define IMAI_DATAOUT_SCALE   1
#define IMAI_DATAOUT_SYMBOLS { }

#define IMAI_KEY_MAX (8)

#define IMAI_RET_SUCCESS    0
#define IMAI_RET_NODATA    -1
#define IMAI_RET_ERROR     -2
#define IMAI_RET_STREAMEND -3

#define IPWIN_RET_SUCCESS    0
#define IPWIN_RET_NODATA    -1
#define IPWIN_RET_ERROR     -2
#define IPWIN_RET_STREAMEND -3

void IMAI_compute(const uint8_t *restrict datain, float *restrict dataout);
void IMAI_finalize(void);
int  IMAI_init(void);

void IMAI_mtb_models_profile_log(void);
void IMAI_mtb_models_print_info(void);
#define IMAI_MAX_MTB_MODELS 4
extern int32_t          IMAI_mtb_models_count;
extern mtb_ml_model_t  *IMAI_mtb_models[IMAI_MAX_MTB_MODELS];

#define IMAI_REGIONS_COUNT 0
#define IMAI_REGIONS_NAMES {}
typedef enum { IMAI_REGIONS_EMPTY } IMAI_Region_t;

typedef enum {
    IMAI_PARAM_UNDEFINED = 0,
    IMAI_PARAM_INPUT     = 1,
    IMAI_PARAM_OUTPUT    = 2,
    IMAI_PARAM_REFERENCE = 3,
    IMAI_PARAM_HANDLE    = 7,
} IMAI_param_attrib;

#endif /* MODUSMATE_PERALGO_MODEL_H */
